### ISSUE TITLE
请问在线音频播放您实现了吗，我copy代码后发现无法在线播放音频！！！！

### ISSUE THREAD

**Issue by ZhangLanqiu** [liupeng110/VLCAndroidDemo#1]

**Comment by liupeng110** [comment]
下载到本地试试 
什么格式的，如果只有音频   直接用系统api播放吧   
这个主要是解决视频倍速播放的问题的

**Comment by ZhangLanqiu** [comment]
本地的音频是可以播放的！
是这样的，我现在需要做一个功能，需要实现在线音频和本地音频播放的时候能够进行倍速播放，但是使用 vlc 的话在线音频无法播放！  大神你试过吗，或者说有什么别的库可以推荐下吗？ 麻烦了

**Comment by liupeng110** [comment]
可以播放啊
http://sc1.111ttt.com/2017/4/05/10/298101104389.mp3
